"""JigsawStack service - PDF report generation"""
import httpx
import logging
from models.schemas import EvidenceReport

logger = logging.getLogger(__name__)

JIGSAWSTACK_API_URL = "https://api.jigsawstack.com/v1/ai/html_to_any"


def build_report_html(report: EvidenceReport) -> str:
    """Build an HTML document from the evidence report for PDF conversion."""
    violations_rows = ""
    for v in report.violation_history:
        status_color = "#dc2626" if v.status == "unpaid" else "#16a34a"
        violations_rows += f"""
        <tr>
            <td>{v.date}</td>
            <td>{v.description}</td>
            <td style="color: {status_color}; font-weight: bold;">{v.status.upper()}</td>
            <td style="text-align: right;">{v.fine_amount:,.0f} VND</td>
        </tr>"""

    legal_items = ""
    for ref in report.legal_references:
        legal_items += f"""
        <div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin-bottom: 8px;">
            <strong>{ref.article_number} - {ref.title}</strong>
            <span style="background: #dbeafe; color: #1d4ed8; padding: 2px 8px; border-radius: 12px; font-size: 11px; margin-left: 8px;">
                {ref.relevance*100:.0f}% relevant
            </span>
            <p style="color: #6b7280; margin-top: 4px; font-size: 13px;">{ref.summary}</p>
        </div>"""

    next_steps_items = "".join(f"<li>{s}</li>" for s in report.next_steps)

    risk_color = "#dc2626" if report.risk_score >= 70 else "#ca8a04" if report.risk_score >= 40 else "#16a34a"
    risk_label = "HIGH RISK" if report.risk_score >= 70 else "MODERATE" if report.risk_score >= 40 else "LOW RISK"

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1f2937; }}
        h1 {{ color: #1e40af; border-bottom: 3px solid #1e40af; padding-bottom: 8px; }}
        h2 {{ color: #374151; margin-top: 32px; }}
        .risk-badge {{ display: inline-block; padding: 12px 24px; border-radius: 12px; font-size: 28px; font-weight: bold; color: {risk_color}; border: 2px solid {risk_color}; }}
        .risk-label {{ font-size: 14px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #e5e7eb; font-size: 13px; }}
        th {{ background: #f9fafb; font-weight: 600; color: #6b7280; }}
        .scene-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 12px; }}
        .scene-item label {{ font-size: 12px; color: #6b7280; font-weight: 600; }}
        .scene-item p {{ margin: 4px 0 0; }}
        .footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <h1>GhostDriver Evidence Report</h1>

    <div style="display: flex; align-items: center; gap: 16px; margin: 24px 0;">
        <div class="risk-badge">{report.risk_score:.0f}</div>
        <div>
            <div class="risk-label" style="color: {risk_color};">{risk_label}</div>
            <div style="color: #6b7280; font-size: 12px;">Risk Score</div>
        </div>
    </div>

    <h2>Violation History</h2>
    <table>
        <thead><tr><th>Date</th><th>Description</th><th>Status</th><th style="text-align:right;">Fine</th></tr></thead>
        <tbody>{violations_rows}</tbody>
    </table>

    <h2>Scene Analysis</h2>
    <div class="scene-grid">
        <div class="scene-item"><label>Damage</label><p>{report.scene_analysis.damage_description}</p></div>
        <div class="scene-item"><label>Impact Point</label><p>{report.scene_analysis.impact_point}</p></div>
        <div class="scene-item"><label>Road Conditions</label><p>{report.scene_analysis.road_conditions}</p></div>
        <div class="scene-item"><label>Vehicle Positions</label><p>{report.scene_analysis.vehicle_positions}</p></div>
    </div>

    <h2>Applicable Legal Codes</h2>
    {legal_items}

    <h2>Fault Assessment</h2>
    <p>{report.fault_assessment}</p>

    <h2>Recommended Next Steps</h2>
    <ol>{next_steps_items}</ol>

    <h2>Vietnamese Summary</h2>
    <p style="background: #f0f9ff; padding: 16px; border-radius: 8px; border-left: 4px solid #1e40af;">
        {report.summary_text}
    </p>

    <div class="footer">
        Generated by GhostDriver | AI-Powered Traffic Incident Analysis | LotusHacks 2026
    </div>
</body>
</html>"""
    return html


async def generate_pdf(report: EvidenceReport, api_key: str) -> bytes | None:
    """Generate PDF from evidence report using JigsawStack."""
    if not api_key:
        logger.warning("JigsawStack API key not configured")
        return None

    html = build_report_html(report)

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                JIGSAWSTACK_API_URL,
                json={
                    "html": html,
                    "output": "pdf",
                    "format": "A4",
                    "margin": {"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"},
                },
                headers={
                    "x-api-key": api_key,
                    "Content-Type": "application/json",
                },
            )
            response.raise_for_status()
            return response.content

    except Exception as e:
        logger.error(f"JigsawStack PDF error: {e}")
        return None
